name: PHPUnit

on:
  push:
  pull_request:
  schedule:
    - cron: '0 14 * * 3' # Run Wednesdays at 2pm EST

jobs:
  php-tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        php: [ 8.4, 8.5 ]
        laravel: [ 12.* ]
        dependency-version: [ stable, lowest ]
        include:
          - laravel: 12.*
            testbench: 10.*
          
    timeout-minutes: 10

    name: "${{ matrix.php }} / ${{ matrix.laravel }} (${{ matrix.dependency-version }})"

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, curl, libxml, mbstring, zip, pcntl, bcmath, intl, iconv
          tools: composer:v2

      - name: Register composer cache directory
        id: composer-cache-files-dir
        run: |
          echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT  

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: |
            vendor
            ${{ steps.composer-cache-files-dir.outputs.dir }}
          key: ${{ runner.os }}-php-${{ matrix.php }}-laravel-${{ matrix.laravel }}-${{ matrix.dependency-version }}-composer-${{ hashFiles('composer.json') }}
          restore-keys: |
            ${{ runner.os }}-php-${{ matrix.php }}-laravel-${{ matrix.laravel }}-${{ matrix.dependency-version }}-composer-

      - name: Install dependencies
        run: |
          composer require --no-interaction --prefer-dist --no-update "laravel/framework:${{ matrix.laravel }}" "orchestra/testbench:${{ matrix.testbench }}"
          composer update --no-interaction --prefer-dist --with-all-dependencies --prefer-${{ matrix.dependency-version }} 

      - name: Execute tests
        run: vendor/bin/phpunit
